baseURL = "http://xwkwh.github.io/hugo"
languageCode = "en-us"
title = "Toby"
theme = "hugo-coder"

defaultcontentlanguage = "en"

paginate = 20

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "yourdiscussshortname"

[params]
  author = "Toby"
  info = "Don't trust your brain"
  description = "Toby's personal website"
  keywords = "blog,developer,personal"
  avatarurl = "images/avatar.jpg"
  # gravatar = "hit_xwk@126.com"

  favicon_32 = "/img/favicon-32x32.png"
  favicon_16 = "/img/favicon-16x16.png"

  footercontent = "Enter a text here."
  hideFooter = false
  hideCredits = false
  hideCopyright = false
  since = 2019

  enableTwemoji = true

  colorScheme = "dark"
  hidecolorschemetoggle = false

  # customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/xwkwh/"

# Menu links
[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "posts/"
[[menu.main]]
  name = "Projects"
  weight = 4
  url = "projects"
[[menu.main]]
  name = "Contact me"
  weight = 2
  url = "contact/"
[[menu.main]]
  name = "About"
  weight = 3
  url = "about/"
  